### ISSUE TITLE
HashId will duplicate

### ISSUE THREAD

**Issue by kimx** [waynebloss/hashids-tsql#1]
Hi 
I tried to modify function "encode1" .
![1](https://cloud.githubusercontent.com/assets/5724118/10069584/a65663e4-62df-11e5-9d12-ffcf41179e32.png)

Testing 1 million record then I got some duplicate records.
![2](https://cloud.githubusercontent.com/assets/5724118/10069614/e214342e-62df-11e5-88e9-09bdd1c6a287.png)

The query result is right or I made something worng? 
What the setting I can make sure the "HashId" will be always unique?
Please help me thanks you.

**Comment by waynebloss** [comment]
You should re-generate the function from the command line tool instead of editing the SQL function, because the alphabet shown in the generated SQL function is pre-shuffled.

```
npm install -g hashids-tsql

hashids-tsql -s bvqdDBM7rQq6 -n 7 -l abcdefghijklmnopqrstuvwxyz1234567890 -t tests.sql
```

The 2nd command above results in a file that contains:

```sql
CREATE FUNCTION [hashids].[encode1]
(
	@number int
)
RETURNS nvarchar(255)
WITH SCHEMABINDING
AS
BEGIN
	-- Options Data - generated by hashids-tsql
	DECLARE
		@salt nvarchar(255) = N'bvqdDBM7rQq6',
		@alphabet nvarchar(255) = N'049gy5o6l2en8mrwz7k3jvqx',
		@seps nvarchar(255) = N'huiftcsab',
		@guards nvarchar(255) = N'p1d',
		@minHashLength int = 7;
		-- Input Alphabet: N'abcdefghijklmnopqrstuvwxyz1234567890'

-- ....
```

**Comment by kimx** [comment]
Hi waynebloss
Cool! I tried 10 million records and it works.
So it turns out to be I used the wrong way.
Thanks very much for your kindly support.
