### ISSUE TITLE
TSQL functions for decoding 

### ISSUE THREAD

**Issue by kimx** [waynebloss/hashids-tsql#2]
Hi 
So embarrassed.Do you have any plan to write functions for decoding?

**Comment by waynebloss** [comment]
Hello! I'm so sorry, I don't have time to do it right now. I'd love to have it done, but I'm busy with work! If you can figure out how to do it and you want to contribute, feel free to send a pull request.

**Comment by kimx** [comment]
Thanks for your kindly reply.I'll try it myself.

**Comment by waynebloss** [comment]
Also - even if you can figure out just the basic TSQL portion of it - I'll finish building out the Node.js generators for you since that shouldn't take long at all.

**Comment by kimx** [comment]
Cool !

**Comment by waynebloss** [comment]
[Here's the code](https://github.com/ivanakimov/hashids.node.js/blob/master/lib/hashids.js) that I used to decipher the algorithm for encode.

There might be more useful info here - http://hashids.org/

**Comment by waynebloss** [comment]
Also, keep in mind that I pre-generate some of the stuff in the generator, so that TSQL doesn't have to do it everytime - like the pre-generated @seps, @guards, etc.. so part of the code is kind of in Javascript.

**Comment by kimx** [comment]
That' really help,thank you.

**Comment by mikeburgh** [comment]
If anyone still needs this: 

```sql
ALTER FUNCTION "dbo"."hashid_decode" 
(
	@id nvarchar(255)
)
RETURNS @ids TABLE 
(
    -- Columns returned by the function
    pos int identity primary key not null,
    id numeric(26,0) NOT NULL
)
WITH SCHEMABINDING
AS
BEGIN
	-- Options Data - generated by hashids-tsql (make sure matches encode method)
	DECLARE
		@salt nvarchar(255) = N'',
		@alphabet nvarchar(255) = N'',
		@seps nvarchar(255) = N'',
		@guards nvarchar(255) = N''
		
	DECLARE @guardIndex int,
                @sepIndex int,
                @charIndex int,
                @idTemp nvarchar(255), 
                @idTempLen int,
                @alphabetLen numeric(26,0),
                @lottery char(1),  
                @buffer nvarchar(255),
                @char char(1),
                @number numeric(26,0), --Stores our decoded number!
                @loopCount int = 0
        

        --First up split on any gaurds that maybe used
        --This is important as they are the borders for our value
        --eg XXGAAAGXX
        --In the above G is the gaurd char, so cut and remove it
        
        While @loopCount < 2 --Wont mater, since we break anyway, this is just to protect an endless loop!
                BEGIN
                        SET @guardIndex = PATINDEX( '%[' + @guards + ']%', @id  COLLATE SQL_Latin1_General_CP1_CS_AS)
                        
                        --Exit if not found!
                        IF (@guardIndex = 0)
                                BREAK;
                                
                        --First time through the loop, we cut the front off, second time the end
                        IF (@loopCount = 0)
                                SET @id = SUBSTRING(@id,@guardIndex + 1, LEN(@id))
                        ELSE
                                SET @id = SUBSTRING(@id,1, @guardIndex-1)
                         
                        Set @loopCount = @loopCount + 1
                END
        
        --Remove the first char it's the lottery
        SET @lottery = SUBSTRING (@id, 1, 1)
        SET @id = SUBSTRING (@id, 2, LEN(@id))
        
        
        
        --Now we need to get out separators, the value between each one is an ID to decode!
        while LEN(@id) != 0
         BEGIN
                --Find a separator, remove before it, decode that then cut the string!
                SET @sepIndex = PATINDEX( '%[' + @seps + ']%', @id  COLLATE SQL_Latin1_General_CP1_CS_AS)
                
                if (@sepIndex != 0)
                        BEGIN
                                --So we have a separator, cut it out before it and decode that
                                SET @idTemp = SUBSTRING(@id,1, @sepIndex-1)
                                --Shorten our string
                                SET @id = SUBSTRING(@id,@sepIndex + 1, LEN(@id))
                        END
                ELSE
                        BEGIN
                                --So what ever we have left now is the string to decode so grab that, and empty our ID
                                SET @idTemp = @id
                                SET @id = ''
                        END    
        
               --Setup buffer and alphabet (once per decode)
               SET @buffer = @lottery + @salt + @alphabet;
               SET @alphabet = [dbo].[hashid_consistentShuffle](@alphabet, SUBSTRING(@buffer, 1, LEN(@alphabet)))
               SET @alphabetLen = LEN(@alphabet)
               
               --Get each char now from the alphabet and apply the conversion
               
               SET @number = 0
               SET @loopCount = 0
               SET @idTempLen = LEN(@idTemp)
               WHILE LEN(@idTemp) != 0
               BEGIN
                        --Take first char, shortern ID
                        SET @char = SUBSTRING(@idTemp,1,1)
                        SET @idTemp = SUBSTRING(@idTemp,2,LEN(@idTemp))
                        
                        --Find index pos in alphabet
                        SET @charIndex = PATINDEX( '%' + @char + '%', @alphabet COLLATE SQL_Latin1_General_CP1_CS_AS)
                        
                        SET @number = @number + (@charIndex-1) * POWER(@alphabetLen, @idTempLen - @loopCount - 1)
               
                        SET @loopCount = @loopCount + 1
        
               END
               
               insert into @ids (id) values (@number)

         END
        

        return;
END
```

**Comment by waynebloss** [comment]
Nice job @mikeburgh !

I added a link to your comment in the readme.

**Comment by kimx** [comment]
> If anyone still needs this:
> 
> ```sql
> ALTER FUNCTION "dbo"."hashid_decode" 
> (
> 	@id nvarchar(255)
> )
> RETURNS @ids TABLE 
> (
>     -- Columns returned by the function
>     pos int identity primary key not null,
>     id numeric(26,0) NOT NULL
> )
> WITH SCHEMABINDING
> AS
> BEGIN
> 	-- Options Data - generated by hashids-tsql (make sure matches encode method)
> 	DECLARE
> 		@salt nvarchar(255) = N'',
> 		@alphabet nvarchar(255) = N'',
> 		@seps nvarchar(255) = N'',
> 		@guards nvarchar(255) = N''
> 		
> 	DECLARE @guardIndex int,
>                 @sepIndex int,
>                 @charIndex int,
>                 @idTemp nvarchar(255), 
>                 @idTempLen int,
>                 @alphabetLen numeric(26,0),
>                 @lottery char(1),  
>                 @buffer nvarchar(255),
>                 @char char(1),
>                 @number numeric(26,0), --Stores our decoded number!
>                 @loopCount int = 0
>         
> 
>         --First up split on any gaurds that maybe used
>         --This is important as they are the borders for our value
>         --eg XXGAAAGXX
>         --In the above G is the gaurd char, so cut and remove it
>         
>         While @loopCount < 2 --Wont mater, since we break anyway, this is just to protect an endless loop!
>                 BEGIN
>                         SET @guardIndex = PATINDEX( '%[' + @guards + ']%', @id  COLLATE SQL_Latin1_General_CP1_CS_AS)
>                         
>                         --Exit if not found!
>                         IF (@guardIndex = 0)
>                                 BREAK;
>                                 
>                         --First time through the loop, we cut the front off, second time the end
>                         IF (@loopCount = 0)
>                                 SET @id = SUBSTRING(@id,@guardIndex + 1, LEN(@id))
>                         ELSE
>                                 SET @id = SUBSTRING(@id,1, @guardIndex-1)
>                          
>                         Set @loopCount = @loopCount + 1
>                 END
>         
>         --Remove the first char it's the lottery
>         SET @lottery = SUBSTRING (@id, 1, 1)
>         SET @id = SUBSTRING (@id, 2, LEN(@id))
>         
>         
>         
>         --Now we need to get out separators, the value between each one is an ID to decode!
>         while LEN(@id) != 0
>          BEGIN
>                 --Find a separator, remove before it, decode that then cut the string!
>                 SET @sepIndex = PATINDEX( '%[' + @seps + ']%', @id  COLLATE SQL_Latin1_General_CP1_CS_AS)
>                 
>                 if (@sepIndex != 0)
>                         BEGIN
>                                 --So we have a separator, cut it out before it and decode that
>                                 SET @idTemp = SUBSTRING(@id,1, @sepIndex-1)
>                                 --Shorten our string
>                                 SET @id = SUBSTRING(@id,@sepIndex + 1, LEN(@id))
>                         END
>                 ELSE
>                         BEGIN
>                                 --So what ever we have left now is the string to decode so grab that, and empty our ID
>                                 SET @idTemp = @id
>                                 SET @id = ''
>                         END    
>         
>                --Setup buffer and alphabet (once per decode)
>                SET @buffer = @lottery + @salt + @alphabet;
>                SET @alphabet = [dbo].[hashid_consistentShuffle](@alphabet, SUBSTRING(@buffer, 1, LEN(@alphabet)))
>                SET @alphabetLen = LEN(@alphabet)
>                
>                --Get each char now from the alphabet and apply the conversion
>                
>                SET @number = 0
>                SET @loopCount = 0
>                SET @idTempLen = LEN(@idTemp)
>                WHILE LEN(@idTemp) != 0
>                BEGIN
>                         --Take first char, shortern ID
>                         SET @char = SUBSTRING(@idTemp,1,1)
>                         SET @idTemp = SUBSTRING(@idTemp,2,LEN(@idTemp))
>                         
>                         --Find index pos in alphabet
>                         SET @charIndex = PATINDEX( '%' + @char + '%', @alphabet COLLATE SQL_Latin1_General_CP1_CS_AS)
>                         
>                         SET @number = @number + (@charIndex-1) * POWER(@alphabetLen, @idTempLen - @loopCount - 1)
>                
>                         SET @loopCount = @loopCount + 1
>         
>                END
>                
>                insert into @ids (id) values (@number)
> 
>          END
>         
> 
>         return;
> END
> ```

Super cool, I've tried this great function, it works well.
