### ISSUE TITLE
minHashLength is not properly declared in generated SQL

### ISSUE THREAD

**Issue by rheone** [waynebloss/hashids-tsql#3]
It appears that `minHashLength` is not declared by default, or when specifically set

running any of the follwing

- `hashids-tsql --minHashLength 5 output.sql`
- `hashids-tsql --n 5 output.sql`
- `hashids-tsql output.sql`

generates a declare statement equivalent to the following with no value set

```sql
	DECLARE
		@salt nvarchar(255) = N'kxWBvbzOG6WA',
		@alphabet nvarchar(255) = N'bm8O75aRDg2YldPryEoJx4jGZk3BAK1NWVXpe9Mzn60L',
		@seps nvarchar(255) = N'sITtShfUiFHCcu',
		@guards nvarchar(255) = N'wqvQ',
		@minHashLength int = ;
```

**Comment by waynebloss** [comment]
Fixed in 5e35213570fabee1ece141bbe11eca3cb2f14465

**Comment by waynebloss** [comment]
Released in v0.0.8

**Comment by waynebloss** [comment]
I think this was due to a change in the main `hashids` package, which is used here, but I'm not sure. You can see in the commit that fixed this, now I'm reading minHashLength from `app` instead of from my `hashids` instance. That was my first guess to fix it and it worked.

**Comment by rheone** [comment]
Thanks for the quick turn around.
